version: '3.9'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: ddd_node
      POSTGRES_PASSWORD: password
      POSTGRES_USER: ddd_node
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
